export const REQUEST_FLIGHTS = 'REQUEST_FLIGHTS';
export const FLIGHTS_FETCH_SUCCEEDED = 'FLIGHTS_FETCH_SUCCEEDED';
export const ADD_FLIGHT = 'ADD_FLIGHT';
export const SHOW_EDIT_FORM = 'SHOW_EDIT_FORM';
export const HIDE_EDIT_FORM = 'HIDE_EDIT_FORM';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const GET_FLIGHTS_BY_CITY = 'GET_FLIGHTS_BY_CITY';
export const GET_FLIGHTS_BY_STATUS = 'GET_FLIGHTS_BY_STATUS';
